spring.application.name=clienteAPI

#Definindo porta
server.port=9994

# JPA
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#Exibir logs completos
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG

#Springdoc OpenApi 3.1/Swagger 3 - 	
springdoc.swagger-ui.path=/swagger-ui.html  
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.example.clienteAPI.web.controller

#spring.profiles.active=prod
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfigurations
