spring.application.name=clienteStorage

#Informacoes para conectar base de dados
#url de acesso ao banco
spring.datasource.url=jdbc:h2:mem:databaseOficial

#classe driver
spring.datasource.driverClassName=org.h2.Driver

#user e senha do banco
spring.datasource.username=mydb
spring.datasource.password=mypass

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#Definindo porta
server.port=9993

#Springdoc OpenApi 3.1/Swagger 3 - http://localhost:9993/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html  
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.example.clienteStorage.web.httpController

